name: recipe_repository
description: A repository that handles recipe related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  uuid: ^3.0.6
  cloud_firestore: ^4.0.3
  equatable: ^2.0.3
  firebase_storage: ^11.0.3
  json_annotation: ^4.6.0


dev_dependencies:
  # mocktail: ^0.3.0
  test: ^1.21.4
  very_good_analysis: ^3.0.2